### ISSUE TITLE
Attribute definition for function and functional element

### ISSUE THREAD

**Issue by rcasteran** [rcasteran/jarvis4se#16]
**Is your feature request related to a problem? Please describe.**
Allow to add attribute to a function / a data / an element / a state

**Describe the solution you'd like**
Support the following command to declare an attribute:
```
<Attribute name> is an attribute.
The type of <Attribute name> is <Attribute type>.
```

Support the following command to describe an object with an attribute:
```
The <Attribute name> of <Object name> is <Attribute value>
```
 
**Describe alternatives you've considered**
None

**Comment by Not2behere** [comment]
Does it have to be displayed within diagrams also ? If this the case, i've to check if this is possible and how for each type of diagrams with plantuml (TBC).

**Comment by Not2behere** [comment]
So after having checked possibilities offered by Plantuml, see below and let me know.

1. For state:

```plantuml, ignore
@startuml
[*] --> State1
State1 --> [*]
State1 : attribute : value
@enduml
```
![PlantUML model](http://www.plantuml.com/plantuml/svg/SoWkIImgAStDuOhMYbNGrRLJ22v9B4arv89GO16W38nhfP1OKbAKcLHQaWfaboNcbAPoEQJcfG0D0000)

2. For function:

```plantuml, ignore
@startuml
object user
user : attribute = value
@enduml
```
![PlantUML model](http://www.plantuml.com/plantuml/svg/SoWkIImgAStDuOhMYbNGrRLJ22v9B4arv89GO16W38nhfP1OKbAKcLHQaWfaboNcbAPoEQJcfG0D0000)

**Comment by rcasteran** [comment]
First priority is to have attributes on function / functional element.
Nothing to be displayed on sequence diagram, but on context and decomposition diagram.
I renamed the issue accordingly.

An attribute can be added to any objects, no special rules. For example an attribute "A" can be added to function and data and an attribute "B" to function and functional element.

An attribute will have as properties : name, type and value.
The value of the property "value" of an attribute will vary according to the described object. In the example above, attribute "A" could have a different value for each function it describes.

No rules about the type for the moment, please consider it for the moment as a meaningless string.

**Comment by Not2behere** [comment]
See release 1.1.3 and related commits
