### ISSUE TITLE
Functional interface inheritance

### ISSUE THREAD

**Issue by rcasteran** [rcasteran/jarvis4se#41]
**Is your feature request related to a problem? Please describe.**
Data is allocated to one functional interface only
But same data could be reused for another functional interface in a different situation (ex : CAN communication with production bench in production situation and with distant ECUs in operational situation, where exchanged data could be reused)

**Describe the solution you'd like**
- Add the following new command:
```
<Functional interface 1 name> inherits from <Functional interface 2 name>
```
- Use the attribute _derived_ to store the inheritance link between the two functional interfaces

**Describe alternatives you've considered**
None

**Comment by Not2behere** [comment]
To be tested on 1.3.2
