### ISSUE TITLE
Element inheritance mechanism

### ISSUE THREAD

**Issue by rcasteran** [rcasteran/jarvis4se#57]
**Is your feature request related to a problem? Please describe.**
Add rule mechanism to allow to derive new elements from the created ones

**Describe the solution you'd like**
- Support the inheritance between elements through the following command:
```
<element 1 name> inherits from <element 2 name>
```
Inheritance mechanism must ensure that:
- Every modification of *element 2* is applied to *element 1*
- Any modification of *element 1* does not affect *element 2* and remains at *element 1* level
- *element 1* must have the same type than *element 2* / must be of a sub type of the type of *element 2*, otherwise inheritance failed

**Describe alternatives you've considered**
None

**Comment by Not2behere** [comment]
Question: Since the beginning, only one parent can be set to the child, is this still True ? If i have "E1 inherits from E2" with E2a child of E2, do i have to add E1 as parent too ?

**Comment by rcasteran** [comment]
In fact decomposition of E1 = { child of E1 } U decomposition of E2

**Comment by Not2behere** [comment]
To be tested on 1.3.2
