### ISSUE TITLE
Display diagram for empty view

### ISSUE THREAD

**Issue by rcasteran** [rcasteran/jarvis4se#61]
**Impacted version**
jarvis4se version: 1.3.1

**Describe the bug**
When Jarvis is asked to display a diagram for a view that does not contain any elements (so called empty view), Jarvis displays a diagram containing all available elements instead of displaying a warning message.

**To Reproduce**
Execute the following commands:
```
%%jarvis
with test
F1 is a function
F2 is a function
a is a data
F1 produces a
F2 consumes a
```

```
%%jarvis
with test
under view
show sequence F1, F2
```
Jarvis is indicating that _view_ is a chain.
Jarvis is displaying the following [diagram](http://www.plantuml.com/plantuml/svg/LO-n3i8m34JtV8NvW0xDYAgeWXsnCLkjAL4REt8T47mzWQdTxdJlJhf-DLGhQN7h71bKLlghZ8e9Bc9qmc6UL0gFPrb4uOePttXxnEmEMN5A24Ro0TD2hjOi3Z4Z6znRwBh2CykBGzX7VXVXOF69HhMoqTxLXIRyu2Eq3Q0RQKjkdNSzyLXlV04=) showing F1, F2 and a.

**Expected behavior**
Jarvis must indicate that _view_ is a view, not a chain
Jarvis must indicate that _view_ is empty (does not contain any elements)

**Desktop (please complete the following information):**
- Browser: Chrome
- Browser version: 100.0.4896.127
- Java: JRE
- Java version: 1.8.0_291

**Comment by Not2behere** [comment]
So now the "chain" element becomes "view". 
Does it have to be renamed also for all user messages for "consider" and xml ?

Does the user message "view does not contain any elements" and not showing diagram, have also to be done for :

- fun_elem/function decomposition
- State/function chains
- fun_elem sequence

**Comment by rcasteran** [comment]
*Does it have to be renamed also for all user messages for "consider" and xml *
Yes

*Does the user message "view does not contain any elements" and not showing diagram, have also to be done for :*
Yes for all
