### ISSUE TITLE
Cannot create new element from extended type

### ISSUE THREAD

**Issue by rcasteran** [rcasteran/jarvis4se#62]
**Impacted version**
jarvis4se version: 1.3.1

**Describe the bug**
When Jarvis is asked to create a new element from an extended type, Jarvis does nothing: element is not created and no message is displayed

**To Reproduce**
Execute the following commands:
```
%%jarvis
with test
"High level function" extends Function
```
```
%%jarvis
with test
F1 is a "High level function"
```
Jarvis indicates that High level function is a type extending Function for the first command, but indicates nothing for the second command : *F1* is not created.

**Expected behavior**
Jarvis must create *F1* as a "Function" of type "High level function".

**Desktop (please complete the following information):**
- Browser: Chrome
- Browser version: 100.0.4896.127
- Java: JRE
- Java version: 1.8.0_291

**Comment by Not2behere** [comment]
Not implemented yet ;)
