### ISSUE TITLE
Decomposition level does not work

### ISSUE THREAD

**Issue by rcasteran** [rcasteran/jarvis4se#81]
**Impacted version**
jarvis4se version: 1.3.4

**Describe the bug**
Jarvis does not handle the decomposition level on decomposition diagram properly

**To Reproduce**
Please execute the following command:
```
%%jarvis
with test
F1 is a function
F2 is a function
a is a data
F1 produces a
F2 consumes a
F21 is a function
F22 is a function
F21 composes F2
F22 composes F2
F211 is a function
F212 is a function
F211 composes F21
F212 composes F21
F211 consumes a
F212 produces b
c is a data
F211 produces c
F212 consumes c
F21 consumes a
b is a data
F21 produces b
F22 consumes b
```

Then please execute the following command to show the decomposition of F2:
```
%%jarvis
with test
show decomposition F2
```
Jarvis displays properly F2 and its children and the related flows.
Then please execute the following command to show the decomposition of F2 at level 1:
```
%%jarvis
with test
show decomposition F2 at level 1
```
Jarvis displays properly F2 and its children at level 1, but is not able to connect the flows *a* and *b* to F21

**Expected behavior**
Jarvis must display F2 and its children at level 1, and must connect the flows *a* and *b* to F21

**Screenshots**
None

**Desktop (please complete the following information):**
- Browser: chrome
- Browser version: 109.0.5414.120
- Java: JRE
- Java version: 1.8.0_291

**Comment by Not2behere** [comment]
Is this the desired output for "show decomposition F2 at level 1" ?
![This is an image](http://www.plantuml.com/plantuml/svg/NT1D2u9040RW-_wAmGwT16VzgWY90e_HhVEeMrcv8-jwYEY_PsQVjtdXVMPW5eqbOzlgB9fJgS5me_gf9aCLhDcg9UMdlU5M5oi-iu4DrNIXxQ6inRWiPe3I2sGy2H15pbNDMcaBJYeTe0Ps4kRpjDMvBLadoNKWNNlgHI76WhEZoll-2_oA9v2-3Fm9XY5-0Hm0_eBRGCAe4v4N-nyoY3_ms31otQI_FODCxDuPkqnYeNJHVUWE)

**Comment by rcasteran** [comment]
Yes, indeed.

**Comment by Not2behere** [comment]
Ok, i'm not able to reproduce the bug and jarvis4se is already displaying the diagram expected:

> Is this the desired output for "show decomposition F2 at level 1" ? ![This is an image](https://camo.githubusercontent.com/b29b1c9ba190fa42e687e5a29b8b1954da790aa688968d0a2e0a12f91f3fe767/687474703a2f2f7777772e706c616e74756d6c2e636f6d2f706c616e74756d6c2f7376672f4e54314432753930343052572d5f77416d4777543136567a6757593930655f48685645654d726376382d6a775945595f507351566a746458564d5057356571624f7a6c674239664a6753356d655f67663961434c6844636739554d646c55354d356f692d69753444724e4958785136696e52576950653349327347793248313570624e444d6361424a59655465305073346b52706a444d76424c61646f4e4b574e4e6c67484937365768455a6f6c6c2d325f6f413976322d33466d395859352d30486d305f654252474341653476344e2d6e796f59335f6d7333316f7451495f464f4443784475506b716e59654e4a4856555745)

**Comment by rcasteran** [comment]
OK, now I got it.
Problem is that "show decomposition F2 at level 1" does not display the right diagram if you run it right after the declaration.
I created a new regression test to highlight this called "test_fun_decomposition_level"

**Comment by rcasteran** [comment]
Please fix this issue by fixing the non regression test

**Comment by rcasteran** [comment]
test_fun_decomposition_level has been renamed into test_issue_81 with #83
