### ISSUE TITLE
add created object to view for decomposition diagram of functional element

### ISSUE THREAD

**Issue by rcasteran** [rcasteran/jarvis4se#9]
**Is your feature request related to a problem? Please describe.**
View can be define with the command "under" when creating an object.

**Describe the solution you'd like**
We need a new command "consider" to add an already created object into a view.
This view will be used to filter objects on a decomposition diagram of a functional element

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Not2behere** [comment]
It has to be integrated for almost all objects and diagrams so this a big feature, would be better to split this issue per objects/diagrams in order to implement/test it step-by-step with priority order.

**Comment by rcasteran** [comment]
First priority is decomposition diagram of a functional element.
Goal is to be able to filter childs of a functional element, the allocated function to these childs, and data exchanged by these functions.
I renamed the issue accordingly
